# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Layer 2 (Orchestrators) - we need to manually register these since they are outside src/
    Nexus\TenantOperations\:
        resource: '../../../orchestrators/TenantOperations/src/'
        exclude: '../../../orchestrators/TenantOperations/src/{DTOs,Contracts,Exceptions}'

    # Explicitly bind interfaces to implementations
    Nexus\Tenant\Contracts\TenantQueryInterface: '@App\Repository\TenantRepository'
    Nexus\Tenant\Contracts\TenantPersistenceInterface: '@App\Infrastructure\Persistence\TenantPersistence'
    
    # L2 Adapters
    Nexus\TenantOperations\Contracts\TenantCreatorAdapterInterface: '@App\Infrastructure\Operations\TenantCreatorAdapter'
    Nexus\TenantOperations\Contracts\AdminCreatorAdapterInterface: '@App\Infrastructure\Operations\AdminCreatorAdapter'
    Nexus\TenantOperations\Contracts\CompanyCreatorAdapterInterface: '@App\Infrastructure\Operations\CompanyCreatorAdapter'
    Nexus\TenantOperations\Contracts\SettingsInitializerAdapterInterface: '@App\Infrastructure\Operations\SettingsInitializerAdapter'
    Nexus\TenantOperations\Contracts\FeatureConfiguratorAdapterInterface: '@App\Infrastructure\Operations\FeatureConfiguratorAdapter'
    Nexus\TenantOperations\Contracts\AuditLoggerAdapterInterface: '@App\Infrastructure\Operations\AuditLoggerAdapter'

    # L2 Rules & DataProvider dependencies
    Nexus\TenantOperations\Contracts\TenantCodeCheckerInterface: '@App\Infrastructure\Operations\TenantUniquenessChecker'
    Nexus\TenantOperations\Contracts\TenantDomainCheckerInterface: '@App\Infrastructure\Operations\TenantUniquenessChecker'
    Nexus\TenantOperations\Contracts\TenantQueryAdapterInterface: '@App\Infrastructure\Operations\TenantOperationsDataProvider'
    Nexus\TenantOperations\Contracts\SettingsQueryAdapterInterface: '@App\Infrastructure\Operations\TenantOperationsDataProvider'
    Nexus\TenantOperations\Contracts\FeatureQueryAdapterInterface: '@App\Infrastructure\Operations\TenantOperationsDataProvider'
